services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    # Les volumes permettent les changements en temps réel
    volumes:
      - ./front:/app
      - /app/node_modules
    command: npm run dev
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./back:/app
      - /app/node_modules
    command: npm run dev
  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

#pour lancer le container : docker compose up --build
#pour stopper le container : docker compose down
#pour voir les logs : docker compose logs -f
#pour voir les conteneurs : docker ps