services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    # Les volumes permettent les changements en temps réel
    volumes:
      - ./front:/app
      - /app/node_modules
    command: npm run dev
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./back:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run dev"

#pour lancer le container : docker compose up --build
#pour stopper le container : docker compose down
#pour voir les logs : docker compose logs -f
#pour voir les conteneurs : docker ps