version: '3.8'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  #pour lancer le container : docker compose up --build
  #pour stopper le container : docker compose down
